 //   <nav className="navbar navbar-expand-lg">
  //   <div
  //     className="navbar-collapse collapse grow items-center mx-auto flex-col-reverse"
  //     id="navbarSupportedContentY"
  //   >
  //       <a href="/">
  //         <button
  //           type="button"
  //           className="
  //                   inline-block
  //                   px-6
  //                   py-2.5
  //                   bg-transparent
  //                   text-black
  //                   font-medium text-xs
  //                   leading-tight
  //                   uppercase
  //                   rounded
  //                   focus:outline-none
  //                   focus:ring-0
  //                   transition
  //                   duration-300
  //                   ease-in-out
  //                   "
  //         >
  //           Главная
  //         </button>
  //       </a>
  //       <a href="/">
  //         <button
  //           type="button"
  //           className="
  //                   inline-block
  //                   px-6
  //                   py-2.5
  //                   bg-transparent
  //                   text-black
  //                   font-medium text-xs
  //                   leading-tight
  //                   uppercase
  //                   rounded
  //                   focus:outline-none
  //                   focus:ring-0
  //                   transition
  //                   duration-300
  //                   ease-in-out
  //                   "
  //         >
  //           СЭД
  //         </button>
  //       </a>

  //       <button
  //         type="button"
  //         className="
  //                   inline-block
  //                   px-6
  //                   py-2.5
  //                   bg-transparent
  //                   text-black
  //                   font-medium text-xs
  //                   leading-tight
  //                   uppercase
  //                   rounded
  //                   focus:outline-none
  //                   focus:ring-0
  //                   transition
  //                   duration-300
  //                   ease-in-out
  //                   "
  //       >
  //         Тех. поддержка
  //       </button>

  //       <button
  //         type="button"
  //         className="
  //                   inline-block
  //                   px-6
  //                   py-2.5
  //                   bg-transparent
  //                   text-black
  //                   font-medium text-xs
  //                   leading-tight
  //                   uppercase
  //                   rounded
  //                   focus:outline-none
  //                   focus:ring-0
  //                   transition
  //                   duration-300
  //                   ease-in-out
  //                   "
  //       >
  //         Почта
  //       </button>

  //       {/* <div className="flex justify-center">
  //         <div>
  //           <div className="dropdown relative">
  //             <button
  //               className="dropdown-toggle px-6 py-2.5
  //                             text-black
  //                             font-medium
  //                             text-xs
  //                             leading-tight
  //                             uppercase
  //                             rounded
  //                             shadow-md
  //                             transition
  //                             duration-150
  //                             ease-in-out
  //                             flex
  //                             items-center
  //                             whitespace-nowrap
  //                             "
  //               type="button"
  //               id="dropdownMenuButton1"
  //               data-bs-toggle="dropdown"
  //               aria-expanded="false"
  //             >
  //               Справочные системы
  //             </button>
  //             <ul
  //               className="
  //                             dropdown-menu
  //                             min-w-max
  //                             absolute
  //                             hidden
  //                             bg-white
  //                             text-base
  //                             z-50
  //                             float-left
  //                             py-2
  //                             list-none
  //                             text-left
  //                             rounded-lg
  //                             shadow-lg
  //                             mt-1
  //                             m-0
  //                             bg-clip-padding
  //                             border-none
  //                             "
  //               aria-labelledby="dropdownMenuButton1"
  //             >
  //               <li>
  //                 <a
  //                   className="
  //                                 dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //                   href="/"
  //                 >
  //                   Шаблоны форм статической отчетности
  //                 </a>
  //               </li>
  //               <li>
  //                 <a
  //                   className="
  //                                 dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //                   href="/"
  //                 >
  //                   Шаблоны форм статической отчетности
  //                 </a>
  //               </li>
  //               <li>
  //                 <a
  //                   className="
  //                                 dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //                   href="/"
  //                 >
  //                   Another action
  //                 </a>
  //               </li>
  //               <li>
  //                 <a
  //                   className="
  //                                 dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //                   href="/"
  //                 >
  //                   Something else here
  //                 </a>
  //               </li>
  //             </ul>
  //           </div>
  //         </div>
  //       </div>
  //       <div className="flex justify-center">
  //         <div className="dropdown relative">
  //           <button
  //             className="dropdown-toggle px-6 py-2.5
  //                             text-black
  //                             font-medium
  //                             text-xs
  //                             leading-tight
  //                             uppercase
  //                             rounded
  //                             shadow-md
  //                             transition
  //                             duration-150
  //                             ease-in-out
  //                             flex
  //                             items-center
  //                             whitespace-nowrap
  //                             "
  //             type="button"
  //             id="dropdownMenuButton1"
  //             data-bs-toggle="dropdown"
  //             aria-expanded="false"
  //           >
  //             Справочные материалы
  //           </button>
  //           <ul
  //             className="
  //                             dropdown-menu
  //                             min-w-max
  //                             absolute
  //                             hidden
  //                             bg-white
  //                             text-base
  //                             z-50
  //                             float-left
  //                             py-2
  //                             list-none
  //                             text-left
  //                             rounded-lg
  //                             shadow-lg
  //                             mt-1
  //                             m-0
  //                             bg-clip-padding
  //                             border-none
  //                             "
  //             aria-labelledby="dropdownMenuButton1"
  //           >
  //             <li>
  //               <a
  //                 className="
  //                                 dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //                 href="/"
  //               >
  //                 Action
  //               </a>
  //             </li>
  //             <li>
  //               <a
  //                 className="
  //                                 dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //                 href="/"
  //               >
  //                 Another action
  //               </a>
  //             </li>
  //             <li>
  //               <a
  //                 className="
  //                                 dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //                 href="/"
  //               >
  //                 Something else here
  //               </a>
  //             </li>
  //           </ul>
  //         </div>
  //       </div>
  //       <div className="flex justify-center">
  //         <div>
  //           <div className="dropdown relative">
  //             <button
  //               className="
  //                                 dropdown-toggle
  //                                 px-6
  //                                 py-2.5
  //                                 text-black
  //                                 font-medium
  //                                 text-xs
  //                                 leading-tight
  //                                 uppercase
  //                                 rounded
  //                                 shadow-md
  //                                 transition
  //                                 duration-150
  //                                 ease-in-out
  //                                 flex
  //                                 items-center
  //                                 whitespace-nowrap
  //                                 "
  //               type="button"
  //               id="dropdownMenuButton1"
  //               data-bs-toggle="dropdown"
  //               aria-expanded="true"
  //             >
  //               Образцы документов
  //             </button>
  //             <ul
  //               className="
  //                 dropdown-menu 
  //                 min-w-max
  //                 absolute
  //                 hidden
  //                 bg-white
  //                 text-base
  //                 z-50
  //                 float-left
  //                 py-2
  //                 list-none
  //                 text-left
  //                 rounded-lg
  //                 shadow-lg
  //                 mt-1
  //                 m-0
  //                 bg-clip-padding
  //                 border-none
  //                 "
  //               aria-labelledby="dropdownMenuButton1"
  //             >
  //               <li>
  //                 <a
  //                   className="
  //                                     dropdown-item
  //                                     text-sm
  //                                     py-2
  //                                     px-4
  //                                     font-normal
  //                                     block
  //                                     w-full
  //                                     whitespace-nowrap
  //                                     bg-transparent
  //                                     text-gray-700
  //                                     hover:text-red-700
  //                                     hover:bg-gray-100
  //                                     "
  //                   href="/"
  //                 >
  //                   Action
  //                 </a>
  //               </li>
  //               <li>
  //                 <a
  //                   className="
  //                                     dropdown-item
  //                                     text-sm
  //                                     py-2
  //                                     px-4
  //                                     font-normal
  //                                     block
  //                                     w-full
  //                                     whitespace-nowrap
  //                                     bg-transparent
  //                                     text-gray-700
  //                                     hover:text-red-700
  //                                     hover:bg-gray-100
  //                                     "
  //                   href="/"
  //                 >
  //                   Another action
  //                 </a>
  //               </li>
  //               <li>
  //                 <a
  //                   className="
  //                                     dropdown-item
  //                                     text-sm
  //                                     py-2
  //                                     px-4
  //                                     font-normal
  //                                     block
  //                                     w-full
  //                                     whitespace-nowrap
  //                                     bg-transparent
  //                                     text-gray-700
  //                                     hover:text-red-700
  //                                     hover:bg-gray-100
  //                                     "
  //                   href="/"
  //                 >
  //                   Something else here
  //                 </a>
  //               </li>
  //             </ul>
  //           </div>
  //         </div>
  //       </div>
  //       <div className="dropdown relative">
  //         <button
  //           className="dropdown-toggle px-6 py-2.5
  //                             text-black
  //                             font-medium
  //                             text-xs
  //                             leading-tight
  //                             uppercase
  //                             rounded
  //                             shadow-md
  //                             transition
  //                             duration-150
  //                             ease-in-out
  //                             flex
  //                             items-center
  //                             whitespace-nowrap
  //                             "
  //           type="button"
  //           id="dropdownMenuButton1"
  //           data-bs-toggle="dropdown"
  //           aria-expanded="false"
  //         >
  //           Центр ИТ ЮО
  //         </button>
            
  //         <ul
  //           className="
  //                             dropdown-menu
  //                             min-w-max
  //                             absolute
  //                             hidden
  //                             bg-white
  //                             text-base
  //                             z-50
  //                             float-left
  //                             py-2
  //                             list-none
  //                             text-left
  //                             rounded-lg
  //                             shadow-lg
  //                             mt-1
  //                             m-0
  //                             bg-clip-padding
  //                             border-none
  //                             "
  //           aria-labelledby="dropdownMenuButton1"
  //         >
  //           <li>
  //             <a
  //               className="
  //                                 dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //               href="cit"
  //             >
  //               Информационное обеспечение
  //             </a>
              
  //           </li>
  //           <li>
  //             <a
  //               className="
  //                                 dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //               href="/"
  //             >
  //               Another action
  //             </a>
  //           </li>
  //           <li>
  //             <a
  //               className="
  //                                 dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //               href="/"
  //             >
  //               Something else here
  //             </a>
  //           </li>
  //         </ul>
  //       </div>
  //       <div className="dropdown relative">
  //         <button
  //           className="dropdown-toggle px-6 py-2.5
  //                             text-black
  //                             font-medium
  //                             text-xs
  //                             leading-tight
  //                             uppercase
  //                             rounded
  //                             shadow-md
  //                             transition
  //                             duration-150
  //                             ease-in-out
  //                             flex
  //                             items-center
  //                             whitespace-nowrap                                    
  //                             "
  //           type="button"
  //           id="dropdownMenuButton1"
  //           data-bs-toggle="dropdown"
  //           aria-expanded="false"
  //         >
  //           Военный совет ЮО
  //         </button>
  //         <ul
  //           className="
  //                             dropdown-menu
  //                             min-w-max
  //                             absolute
  //                             hidden
  //                             bg-white
  //                             text-base
  //                             z-50
  //                             float-left
  //                             py-2
  //                             list-none
  //                             text-left
  //                             rounded-lg
  //                             shadow-lg
  //                             mt-1
  //                             m-0
  //                             bg-clip-padding
  //                             border-none
  //                             "
  //           aria-labelledby="dropdownMenuButton1"
  //         >
  //           <li>
  //             <a
  //               className="
  //                                 dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //               href="/"
  //             >
  //               Action
  //             </a>
  //           </li>
  //           <li>
  //             <a
  //               className="
  //                                 dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //               href="/"
  //             >
  //               Another action
  //             </a>
  //           </li>
  //           <li>
  //             <li>
  //               <a
  //                 className="
  //                       dropdown-item
  //                                 text-sm
  //                                 py-2
  //                                 px-4
  //                                 font-normal
  //                                 block
  //                                 w-full
  //                                 whitespace-nowrap
  //                                 bg-transparent
  //                                 text-gray-700
  //                                 hover:text-red-700
  //                                 hover:bg-gray-100
  //                                 "
  //                 href="/"
  //               >
  //                 Something else here
  //               </a>
  //             </li>
  //           </li>
  //         </ul>
  //       </div> */}
  //   </div>
  // </nav>